os: osx
osx_image: xcode8.1

language: generic

before_install:
  - brew update
  - brew upgrade python
  - virtualenv .tox
  - source .tox/bin/activate

# command to install dependencies
install:
  - pip install tox-travis

# command to run tests
script: tox
