---

# Obtain a token using the instructions found here:
# https://api.slack.com/custom-integrations/legacy-tokens
token:

# Wireless SSID for your work location. Used to detect whether working
# remotely. Any value other than the following is considered remote to work.
work_ssid: vmware

# List of iCal calendar names that represent work events. This is used to
# determine the "In Meeting" status.
work_calendars:
  - Work

# List of iCal calendar names that represent vacation events. This is used to
# determine the "Vacationing" status.
vacation_calendars:
  - Vacation

# Whether or not to include meeting titles in the status text. This affects
# the "In a Meeting" and "Vacationing" statuses.
meeting_title: true

# This list of dictionaries can be configured with various remote work
# locations. For example, if you're working from Starbucks, you could
# automatically set the status text and emoji to something Starbucks-ish.
# Keep in mind, that the emoji given must be part of the emoji set of your
# Slack team.
remote_locations:
  - ssid: Home
    location: Home
    status_text: Working from Home
    status_emoji: ":house_with_garden:"

  # NOTE: Your Slack team needs to have an custom emoji for Starbucks
  - ssid: Google Starbucks
    location: Starbucks
    status_text: Working from Starbucks
    status_emoji: ":starbucks:"
    
  # NOTE: Your Slack team needs to have an custom emoji for Peets
  - ssid: PEETS
    location: Peet's Coffee & Tea
    status_text: Working from Peet's Coffee & Tea
    status_emoji: ":peets:"

# Whether or not debug mode is on.
debug: false
